kind: Service
apiVersion: v1
metadata:
  name: dockernodemicro2
spec:
  selector:
    deployment: dockernodemicro2
  ports:
    -
      protocol: TCP
      port: 80
      targetPort: 3000
      name: http
  type: LoadBalancer
