kind: Service
apiVersion: v1
metadata:
  name: dockernode
spec:
  selector:
    deployment: dockernode
  ports:
    -
      protocol: TCP
      port: 80
      targetPort: 3000
      name: http
  type: LoadBalancer
